naszekolorowanki/forms/user_forms.py
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, Regexp, EqualTo, ValidationError

from naszekolorowanki.models.user_models import User


class LoginForm(FlaskForm):
    username = StringField('Nazwa użytkownika', validators=[DataRequired(message='To pole jest wymagane.')])
    password = PasswordField('Hasło', validators=[DataRequired(message='To pole jest wymagane.'), Length(min=8,
                                                                                                         message='Długość hasła to min 8 znaków.')])
    remember_me = BooleanField('Nie wylogowuj')
    submit = SubmitField('Zaloguj się')


class SignUpForm(FlaskForm):
    username = StringField('Nazwa użytkownika',
                           validators=[DataRequired(message='To pole jest wymagane.'), Length(3, 80),
                                       Regexp('^[A-Za-z0-9_]{3,}$',
                                              message='Nazwa  użytkownika składa się z liter, cyfr, podkreśleń.')])
    password = PasswordField('Hasło', validators=[DataRequired(message='To pole jest wymagane.'),
                                                  Length(min=8, message='Długość hasła to min 8 znaków.'),
                                                  EqualTo('password2', message='Hasło musi pasować.')])
    password2 = PasswordField('Potwierdź hasło', validators=[DataRequired(message='To pole jest wymagane.')])
    submit = SubmitField('Zarejestruj')

    def validate_username(self, username_field):
        if User.query.filter_by(username=username_field.data).first():
            raise ValidationError('Ta nazwa użytkownika już jest zajęta.')


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField('Obecne hasło',
                                 validators=[DataRequired(message='To pole jest wymagane.')])

    new_password = PasswordField('Nowe hasło', validators=[DataRequired(message='To pole jest wymagane.'),
                                                           Length(min=8,
                                                                  message='Długość hasła to min 8 znaków.'),
                                                           EqualTo('new_password2', message='Hasło musi pasować.')])
    new_password2 = PasswordField('Potwierdź nowe hasło', validators=[DataRequired(message='To pole jest wymagane.')
                                                                      ])
    submit = SubmitField('Zatwierdź')

    def validate_old_password(self, password):
        user = User.query.filter_by(username=current_user.username).first_or_404()
        if not user.check_password(password.data):
            raise ValidationError('Nieprawidłowe hasło')


class DeleteUserForm(FlaskForm):
    password = PasswordField('Hasło', validators=[DataRequired(message='To pole jest wymagane.'), Length(min=8,
                                                                                                         message='Długość hasła to min 8 znaków.')])
    submit = SubmitField('Skasuj Twoje konto')

    @staticmethod
    def validate_password(self, password):
        user = User.query.filter_by(username=current_user.username).first_or_404()
        if not user.check_password(password.data):
            raise ValidationError('Nieprawidłowe hasło')

naszekolorowanki/views/auth_views.py
from os import abort

from flask import Blueprint, request, url_for, render_template, flash, current_app
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.utils import redirect

from naszekolorowanki import db
from naszekolorowanki.forms.user_forms import LoginForm, SignUpForm, ChangePasswordForm, DeleteUserForm
from naszekolorowanki.models.user_models import User

bp_auth = Blueprint('auth', __name__, url_prefix='/auth')


@bp_auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if not User.query.filter(User.username == current_app.config["USER_NAME"]).first():
        user = User(username=current_app.config["USER_NAME"], password=current_app.config["USER_PASSWORD"])
        db.session.add(user)
        db.session.commit()

    if form.validate_on_submit():
        user = User.get_by_username(form.username.data)
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            return redirect(request.args.get('next') or url_for('main.home'))

    return render_template('login.html', form=form)


@bp_auth.route('/signup', methods=['GET', 'POST'])
@login_required
def signup():
    form = SignUpForm()

    if form.validate_on_submit():
        user = User(username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.home'))

    return render_template('signup.html', form=form)


@bp_auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@bp_auth.route('/user/<username>')
@login_required
def user(username):
    user_db = User.query.filter_by(username=username).first_or_404()
    form = DeleteUserForm()
    return render_template('user.html', user=user_db, form=form)


@bp_auth.route('/edit_user/<username>', methods=['GET', 'POST'])
@login_required
def edit_user(username):
    user_db = User.query.filter_by(username=username).first_or_404()

    if current_user != user_db:
        abort(403)

    form = ChangePasswordForm()

    if form.validate_on_submit():
        user_db.password = form.new_password.data
        db.session.commit()
        flash(f'Twoje hasło zostało zmienione.', 'info')
        return redirect(url_for('auth.user', username=username))

    return render_template('edit_user.html', form=form, user=user_db)


@bp_auth.route('/delete_user/<username>', methods=['POST'])
@login_required
def delete_user(username):
    user_db = User.query.filter_by(username=username).first_or_404()

    if current_user != user_db:
        abort(403)

    form = DeleteUserForm()

    if form.validate_on_submit():
        db.session.delete(user_db)
        db.session.commit()
        flash(f'Usunąłeś konto ', 'danger')
        return redirect(url_for('main.home'))
    flash('Nieprawidłowe hasło.', 'danger')
    return redirect(url_for('auth.user', username=current_user.username))

naszekolorowanki/views/image_views.py
import os
import time

from flask import Blueprint, flash, redirect, url_for, render_template, send_from_directory, current_app
from flask_login import login_required
from sqlalchemy import desc

from naszekolorowanki import db, login_manager
from naszekolorowanki.forms.image_forms import ImageForm, EditImageForm
from naszekolorowanki.models.image_models import Image
from naszekolorowanki.models.user_models import User
from naszekolorowanki.utils.save_resize import save_resize_image


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


bp_image = Blueprint('image', __name__, url_prefix='/image')


@bp_image.route('/list_to_accept', methods=['GET'])
@login_required
def list_to_accept():
    images = Image.query.filter_by(status=False).order_by(desc(Image.date)).all()
    return render_template('list.html', images=images, title='Obrazki do zaakceptowania',
                           fn_name="list_to_accept")


@bp_image.route('/list_accepted', methods=['GET'])
@login_required
def list_accepted():
    images = Image.query.filter_by(status=True).order_by(desc(Image.date)).all()
    return render_template('list.html', images=images, title='Zaakceptowane obrazki',
                           fn_name="list_accepted")


@bp_image.route('/add_image', methods=['GET', 'POST'])
def add_image():
    form = ImageForm()

    if form.validate_on_submit():
        filename = save_resize_image(form.image, form.username.data)
        image = Image(username=form.username.data, thumbnail=filename[0], image=filename[1],
                      description=form.description.data)
        db.session.add(image)
        db.session.commit()
        flash(f'Twój obrazek został dodany. '
              f'Po naszej akceptacji zostanie wyświetlony na stronie głównej.', 'secondary')
        return redirect(url_for('main.home'))

    return render_template('add_image.html', form=form)


@bp_image.route('/edit_image/<int:image_id>/<string:fn_name>/<string:title>', methods=['GET', 'POST'])
@login_required
def edit_image(image_id, fn_name, title):

    image = Image.query.get_or_404(image_id)
    form = EditImageForm(obj=image)
    file = os.path.join(current_app.config['IMAGE_RESIZED'], image.image)
    img_size = os.path.getsize(file) / 1024 / 1024
    img_created = time.strftime("%d.%m.%Y godz.%H:%m", time.localtime(os.path.getctime(file)))

    if form.validate_on_submit():
        form.populate_obj(image)
        db.session.commit()
        return redirect(url_for(f'image.{fn_name}'))
    return render_template('edit_image.html', form=form, image=image, fn_name=fn_name,
                           title=title.lower(), img_size=round(img_size, 3), img_created=img_created)


@bp_image.route('/delete_image/<int:image_id>/<string:fn_name>', methods=['GET'])
@login_required
def delete_image(image_id, fn_name):
    image = Image.query.get_or_404(image_id)
    paths = [os.path.join(current_app.config["THUMBNAIL"], image.thumbnail),
             os.path.join(current_app.config["IMAGE_RESIZED"], image.image)]
    for path in paths:
        os.remove(path)
    db.session.delete(image)
    db.session.commit()
    flash('Usunięto obrazek.', 'danger')
    return redirect(url_for(f'image.{fn_name}'))


@bp_image.route('/uploads/<path:filename>', methods=['GET', 'POST'])
def download(filename):
    uploads = os.path.join(current_app.config["IMAGE_RESIZED"])
    return send_from_directory(directory=uploads, filename=filename)

naszekolorowanki/views/main_views.py
from flask import Blueprint, render_template, send_from_directory, request, current_app
from sqlalchemy import desc, or_

from naszekolorowanki.forms.filter_form import FilterForm
from naszekolorowanki.models.image_models import Image

bp_main = Blueprint('main', __name__, url_prefix='/')


@bp_main.route('/', methods=['GET'])
def home():
    form = FilterForm(request.args, meta={"csrf": False})
    page = request.args.get('page', 1, type=int)
    images = Image.query.filter(or_(Image.username.contains(f'{form.search.data.strip()}'),
                                    Image.description.contains(f'%{form.search.data.strip()}%'))) \
        .filter_by(status=True).order_by(desc(Image.date)).paginate(page=page, per_page=9)
    return render_template('home.html', images=images, form=form)


@bp_main.route("/uploads/<filename>")
def uploads(filename):
    if filename.rsplit('.', 1)[0][-1] == 'i':
        path = current_app.config["IMAGE_RESIZED"]
    else:
        path = current_app.config["THUMBNAIL"]
    return send_from_directory(path, filename)


@bp_main.route("/cookies")
def cookies():
    return render_template('cookies.html')

naszekolorowanki/templates/_cookie.html
<div class="modal modal-cookie "  id="modalCookie">
  <div class="modal-dialog modal-xl mb-0 mw-100 mh-15 fixed-bottom">
    <div class="modal-content">

      <div class="modal-body  cookie-our  pb-0">
         <div class="row pl-3">
           <div class="col-9 ">
        <p><span>Ta strona korzysta z ciasteczek, aby świadczyć usługi na najwyższym poziomie.
        Warunki przechowywania lub dostępu do plików cookies można zmienić w ustawieniach przeglądarki - niedokonanie zmian ustawień przeglądarki jest jednoznaczne z wyrażeniem zgody na ich zapisywanie. Więcej o <a class=" cookie-links" href="{{ url_for('main.cookies') }} ">ciasteczkach.</a></span></p>

</div>
<div class="col-3 d-flex justify-content-center align-items-center">

        <button type="button" class="btn btn-info" id="acceptCookie">Zgadzam się</button>
 </div></div></div>
    </div>
  </div>
</div>

naszekolorowanki/templates/_flash.html
<div class="row">
    <div class="col-12">
        {% with messages=get_flashed_messages(with_categories=True) %}
        {% if messages %}
        {% for type, message in messages %}

        <div class="alert alert-{{type}} alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        {% endfor %}
        {% endif %}
        {% endwith %}
    </div>
</div>

naszekolorowanki/templates/_footer.html
<footer class="container main-footer m-0">
    {% block footer %}

    <div class="card-body ">
        <div class="row">
            <div class="col">
                <li class="list-unstyled float-left">Copyright&#169;2020 Nasze kolorowanki</li>
            </div>
            <div class="col d-flex justify-content-center">
                <li class="list-unstyled align-content-center">
                    <a class="nav-link admin" href="{{ url_for('auth.login') }} ">Administracja</a>
                </li>
            </div>
            <div class="col d-flex justify-content-center">
                <li class="list-unstyled align-content-center">
                    <a class="nav-link cookie-link" href="{{ url_for('main.cookies') }} ">Ciasteczka</a>
                </li>
            </div>

            <div class="col">
                <li class="list-unstyled float-right"> naszekolorowanki@gmail.com</li>
            </div>
        </div>
    </div>

    {% endblock %}
</footer>

naszekolorowanki/templates/_form_macros.html
{% macro render_field(field) %}

<div class="form-group">
    {% with cls = "form-control is-invalid" if field.errors else "form-control" %}
        {% if field.widget.input_type == 'submit' %}
            {% set cls = "btn btn-info custom-btn" %}
        {% endif %}

        {% if field.widget.input_type == 'file' %}
            {% set cls = "form-control-file" %}
        {% endif %}


    <!--    selct radiobatton, wewnątrz makro można robić include-->
        {% if field.widget.input_type == 'checkbox' %}
            {{ field }}
            {{ field.label }}


        {% else %}
            {% if field.widget.input_type != 'hidden' and field.widget.input_type != 'submit' %}
                {{ field.label(class="form-label") }}:
            {% endif %}

            {{ field(class=cls) }}

        {% endif %}
    {% endwith %}

    {% for error in field.errors %}
    <div class="invalid-feedback"> {{ error }}</div>
    {% endfor %}

</div>
{% endmacro %}


{% macro error_messages(errors, form) %}
{% if  errors %}
<div class="alert alert-danger" role="alert">
    {% for field in errors %}
        <b> Formularz </b>{{ form[field].label | capitalize }} <b> pokazuje błąd:</b>
            {% for error in errors[field] %}
                {{ error }} <br>
            {% endfor %}
    {% endfor %}
</div>
{% endif %}


{% endmacro %}

naszekolorowanki/templates/_header.html
<header class="main-header ">
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">

            <a class="navbar-brand" href="{{ url_for('main.home') }} "><img class="logo coloring-book"
                                                                            src="{{ url_for('static', filename='img/logo.png')}}"
                                                                            alt="logo"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" style="color: #345163" aria-current="page"
                           href="{{ url_for('main.home') }} ">Strona główna</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link " style="color: #345163" href="{{ url_for('image.add_image') }} ">Dodaj pracę
                        </a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link " style="color: #345163"
                           href="{{ url_for('image.list_to_accept', username=current_user.username) }} ">Prace do
                            akceptacji</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " style="color: #345163"
                           href="{{ url_for('image.list_accepted', username=current_user.username) }} ">Prace
                            zaakceptowane</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " style="color: #345163"
                           href="{{ url_for('auth.user', username=current_user.username) }} ">Twoje konto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " style="color: #345163" href="{{ url_for('auth.logout') }} ">Wyloguj się</a>
                    </li>

                    {% endif %}

                </ul>
            </div>
            <h1><i>Nasze kolorowanki</i></h1>

    </nav>

</header>

naszekolorowanki/templates/_modal-form.html
<div class="modal fade" id="{{modal_id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Aby usunąć to konto - wprowadź hasło</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {% with action = url_for("auth.delete_user", username=user.username) %}

                {% include '_form.html' %}
                {% endwith %}
            </div>

        </div>
    </div>
</div>

naszekolorowanki/templates/_modal_image.html
<div class="modal fade" id="modal{{count.value }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <button type="button" class="close close-button" data-dismiss="modal" aria-label="Close"></button>
    <img class="modal-dialog  modal-content  z-depth-1-half embed-responsive-item rounded full-view" src="{{home_image}}"
         allowfullscreen>
</div>

naszekolorowanki/templates/add_image.html
{% extends '_base.html' %}


{% block content %}

<div class="col-6">
    {% with enctype = True %}
    {% include '_form.html' %}
    {% endwith %}

    <p><small>
        Dodając obrazek, potwierdzasz, że jesteś jego autorem oraz
        wyrażasz zgodę na publikację i ewentualną modyfikację obrazka na naszej stronie.
        Jeśli będziesz chciał usunąć Twój obrazek z naszej strony skontaktuj się z nami: naszekolorowanki@gmail.com.<br>
        Zastrzegamy sobie prawo do nie publikowania Twojego obrazka oraz usunięcia go bez podania przyczyny.
    </small></p>
</div>
{% endblock %}

naszekolorowanki/templates/delete_user.html
{% extends '_base.html' %}
{% from "_form_macros.html" import render_field  %}

{% block content %}
    <h3>Hello <b>{{user.username}}</b></h3>

    <div class="col-6">
        {% include '_form.html' %}
    </div>

{% endblock %}

naszekolorowanki/templates/edit_image.html
{% extends '_base.html' %}
{% from "_form_macros.html" import render_field  %}

{% block content %}
<h3> Edycja - {{ title }}</h3>
<div class="row">

<div class="col-lg-6 col-md-6 mb-4">
    <figure class="figure full-width">

         <a  href="{{ url_for('image.download', filename=image.image, fn_name=fn_name)}}">
        <img class="rounded img-fluid figure-img" alt="Responsive image"
             src="{{ url_for('main.uploads', filename=image.image) }}"></a>
        <figcaption class="figure-caption">
            Nazwa pliku: {{ image.image}}<br>
            Opis: {{image.description }}<br>
            Autor: {{image.username}}<br>
            Wielkość: {{ img_size }} MB <br>
            Utworzone: {{ img_created  }} <br>
            Opis admina: {{image.info}}<br>
             <a class="btn btn-info float-left mb-3 pb-2" href="{{ url_for('image.download', filename=image.image, fn_name=fn_name)}}">Pobierz</a>
        </figcaption>
    </figure>
</div>

<div class="col-lg-6">
    {% include '_form.html' %}


    <br>
    <a class="btn btn-danger float-right mb-3 pb-2" href="{{ url_for('image.delete_image', image_id=image.id, fn_name=fn_name)}}">Usuń
                obrazek</a>
</div></div>



{% endblock %}

naszekolorowanki/templates/edit_user.html
{% extends '_base.html' %}
{% from "_form_macros.html" import render_field  %}

{% block content %}
    <h3>Witaj <b>{{user.username}} !</b></h3>

    <div class="col-6">
        {% include '_form.html' %}
    </div>

{% endblock %}

naszekolorowanki/templates/home.html
{% extends '_base.html' %}

{% block content %}
    </div>
        <form method="get" class="float-right">
            {{form.search}}
            <button class="btn btn-info custom-btn btn-sm btn-search-our" type="submit">Szukaj</button>

        </form>

        <h3 class="p-3">Cześć!</h3>

        <p><span>Widzimy, że odwiedziłeś naszą stronę. Istnieje ona po to, by dzielić się pomysłami na kolorowanki i rysunki. Może ktoś naprawdę się zainspiruje i zostanie wielkim artystą? Miło by było... :) Same bardzo lubimy kolorować, ale czasem miewamy braki weny. Przeglądaj do woli prace innych, możesz też wstawić własne dzieła.</span>
        </p>
        <div class="row my-2 card-wrapper">
            {% set count = namespace(value=0) %}
            {% if images %}

            {% for image in images.items %}
            {% with home_image = url_for('main.uploads', filename=image.image) %}
            {% with home_thumbnail = url_for('main.uploads', filename=image.thumbnail) %}
            {% set count.value = count.value + 1 %}


            <div class="col-lg-4 col-md-6 mb-4">
                <figure class="figure">

                    <a>
                        <img id="myImg" class="rounded img-fluid figure-img z-depth-1 home-page-image" alt="Responsive image"
                             src="{{home_thumbnail}}" data-toggle="modal"
                             data-target="#modal{{count.value }}">
                    </a>
                    <figcaption class="figure-caption font-our">
                        {{image.description }}<br>
                        Autor: {{image.username}}
                    </figcaption>
                </figure>
            </div>
            {% include '_modal_image.html' %}

            {% endwith %}
            {% endwith %}
            {% endfor %}
            {% endif %}
        </div>


        <div class="text-right">
            <a href="{{ url_for('main.home', page=images.prev_num) }}"
               class="btn btn-outline-dark
               {% if images.page == 1 %}disabled{% endif %}">
                &laquo;
            </a>

            {% for page_num in images.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}

                {% if images.page == page_num %}
                    <a href="{{ url_for('main.home', page=page_num) }}"
                       class="btn btn-dark">
                        {{ page_num }}
                    </a>
                {% else %}
                    <a href="{{ url_for('main.home', page=page_num) }}"
                       class="btn btn-outline-dark">
                        {{ page_num }}
                    </a>
                {% endif %}
            {% else %}
            ...
            {% endif %}
            {% endfor %}
            <a href="{{ url_for('main.home', page=images.next_num) }}"
               class="btn btn-outline-dark
               {% if images.page == images.pages %}disabled{% endif %}">
                &raquo;
            </a>
        </div>
        <p class="text-right mt-3">
            Strona {{ images.page }} z {{ images.pages }}
        </p>

    {% endblock %}

    {% block scripts %}
    {{ super() }}</div>
    <script>

    </script>

{% endblock %}

naszekolorowanki/templates/signup.html
{% extends '_base.html' %}
{% from "_form_macros.html" import render_field  %}

{% block content %}

    <div class="col-6">
    {% include '_form.html' %}
    </div>

{% endblock %}

naszekolorowanki/templates/user.html
{% extends '_base.html' %}
{% set modal_id = 'deleteModalForm' %}
{% set btn_id = 'deleteForm' %}

{% block content %}
    <div class="col-6">
    <h3>Cześć <b>{{user.username}}</b></h3><br>
    <a class="btn btn-outline-success"  href="{{ url_for('auth.signup') }} ">Rejestracja nowego admina</a><br><br>
    <a class="btn btn-outline-primary" href="{{ url_for('auth.edit_user', username=current_user.username)}}">Zmień hasło</a><br><br>
    <button class="btn btn-outline-danger"  id="{{btn_id}}" data-target="#{{modal_id}}" data-toggle="modal" >Usuń konto</button>
        <br>

    {% include '_modal-form.html' %} \
{% endblock %}


{% block scripts %}
    {{ super() }}</div>
    <script>
    $('#{{modal_id}}').on('shown.bs.modal', function () {
      $('#{{btn_id}}').trigger('focus')
    })
    </script>

{% endblock %}